name: isetcam-py
channels:
  - conda-forge
dependencies:
  - python=3.12
  - octave
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - imageio
  - tifffile
  - h5py
  - pooch
  - pytest
  - pytest-cov
  - ruff
  - mypy
  - git
  - pip
