from __future__ import annotations

import numpy as np

from pyisetcam import ieParameterOtype
from pyisetcam.utils import blackbody, energy_to_quanta, ie_parameter_otype, param_format, quanta_to_energy, unit_frequency_list


def test_param_format_string_and_key_value_list() -> None:
    assert param_format("Exposure Time") == "exposuretime"
    assert param_format(["Exposure Time", 1, "Some Flag", True]) == ["exposuretime", 1, "someflag", True]


def test_energy_quanta_round_trip() -> None:
    wave = np.array([400.0, 500.0, 600.0])
    energy = np.array([0.2, 0.5, 0.8])
    quanta = energy_to_quanta(energy, wave)
    restored = quanta_to_energy(quanta, wave)
    assert np.allclose(restored, energy)


def test_blackbody_matlab_scaling() -> None:
    wave = np.arange(400.0, 701.0, 10.0)
    spectra = blackbody(wave, np.array([3000.0, 5000.0]))
    assert spectra.shape == (wave.size, 2)
    assert np.all(spectra > 0.0)
    eq_index = int(np.argmin(np.abs(wave - 550.0)))
    assert np.isclose(spectra[eq_index, 0], spectra[eq_index, 1])


def test_unit_frequency_list_matches_matlab_even_and_odd() -> None:
    assert np.allclose(unit_frequency_list(4), np.array([-1.0, -0.5, 0.0, 0.5]))
    assert np.allclose(unit_frequency_list(5), np.array([-1.0, -0.5, 0.0, 0.5, 1.0]))


def test_ie_parameter_otype_handles_direct_prefix_and_unique_params() -> None:
    assert ie_parameter_otype("scene") == ("scene", None)
    assert ie_parameter_otype("oi size") == ("oi", "size")
    assert ie_parameter_otype("pixel/size") == ("pixel", "size")
    assert ie_parameter_otype("pixel width and height") == ("pixel", "widthandheight")
    assert ie_parameter_otype("pixel pd width and height") == ("pixel", "pdwidthandheight")
    assert ie_parameter_otype("width and height") == ("pixel", "widthandheight")
    assert ie_parameter_otype("pd width and height") == ("pixel", "pdwidthandheight")
    assert ie_parameter_otype("size same fill factor") == ("pixel", "sizesamefillfactor")
    assert ie_parameter_otype("size constant fill factor") == ("pixel", "sizeconstantfillfactor")
    assert ie_parameter_otype("size keep fill factor") == ("pixel", "sizekeepfillfactor")
    assert ie_parameter_otype("dark voltage per pixel per sec") == ("pixel", "darkvoltageperpixelpersec")
    assert ie_parameter_otype("wvf_zcoeffs") == ("wvf", "zcoeffs")
    assert ie_parameter_otype("display gamma") == ("display", "gamma")
    assert ie_parameter_otype("dsnu sigma") == ("sensor", "dsnusigma")
    assert ie_parameter_otype("sigma offset fpn") == ("sensor", "sigmaoffsetfpn")
    assert ie_parameter_otype("offset fpn") == ("sensor", "offsetfpn")
    assert ie_parameter_otype("offset") == ("sensor", "offset")
    assert ie_parameter_otype("offset sd") == ("sensor", "offsetsd")
    assert ie_parameter_otype("offset noise value") == ("sensor", "offsetnoisevalue")
    assert ie_parameter_otype("sigma dsnu") == ("sensor", "sigmadsnu")
    assert ie_parameter_otype("sigma gain fpn") == ("sensor", "sigmagainfpn")
    assert ie_parameter_otype("gain fpn") == ("sensor", "gainfpn")
    assert ie_parameter_otype("gain") == ("sensor", "gain")
    assert ie_parameter_otype("gain sd") == ("sensor", "gainsd")
    assert ie_parameter_otype("gain noise value") == ("sensor", "gainnoisevalue")
    assert ie_parameter_otype("sigma prnu") == ("sensor", "sigmaprnu")
    assert ie_parameter_otype("fpn") == ("sensor", "fpn")
    assert ie_parameter_otype("fpn offset gain") == ("sensor", "fpnoffsetgain")
    assert ie_parameter_otype("offset fpn image") == ("sensor", "offsetfpnimage")
    assert ie_parameter_otype("gain fpn image") == ("sensor", "gainfpnimage")
    assert ie_parameter_otype("column fpn parameters") == ("sensor", "columnfpnparameters")
    assert ie_parameter_otype("columnfpn") == ("sensor", "columnfpn")
    assert ie_parameter_otype("column fixed pattern noise") == ("sensor", "columnfixedpatternnoise")
    assert ie_parameter_otype("col fpn") == ("sensor", "colfpn")
    assert ie_parameter_otype("column fpn offset") == ("sensor", "columnfpnoffset")
    assert ie_parameter_otype("col fpn offset") == ("sensor", "colfpnoffset")
    assert ie_parameter_otype("col dsnu") == ("sensor", "coldsnu")
    assert ie_parameter_otype("column fpn gain") == ("sensor", "columnfpngain")
    assert ie_parameter_otype("col fpn gain") == ("sensor", "colfpngain")
    assert ie_parameter_otype("col prnu") == ("sensor", "colprnu")
    assert ie_parameter_otype("col offset fpn") == ("sensor", "coloffsetfpn")
    assert ie_parameter_otype("col offset") == ("sensor", "coloffset")
    assert ie_parameter_otype("col gain fpn") == ("sensor", "colgainfpn")
    assert ie_parameter_otype("col gain") == ("sensor", "colgain")
    assert ie_parameter_otype("responsedr") == ("sensor", "responsedr")
    assert ie_parameter_otype("drdb20") == ("sensor", "drdb20")
    assert ie_parameter_otype("nfilters") == ("sensor", "nfilters")
    assert ie_parameter_otype("filtercolorletters") == ("sensor", "filtercolorletters")
    assert ie_parameter_otype("filtercolorletterscell") == ("sensor", "filtercolorletterscell")
    assert ie_parameter_otype("filterplotcolors") == ("sensor", "filterplotcolors")
    assert ie_parameter_otype("filterspectra") == ("sensor", "filterspectra")
    assert ie_parameter_otype("colorfilters") == ("sensor", "colorfilters")
    assert ie_parameter_otype("infraredfilter") == ("sensor", "infraredfilter")
    assert ie_parameter_otype("irfilter") == ("sensor", "irfilter")
    assert ie_parameter_otype("spectralqe") == ("sensor", "spectralqe")
    assert ie_parameter_otype("sensorspectralsr") == ("sensor", "sensorspectralsr")
    assert ie_parameter_otype("patterncolors") == ("sensor", "patterncolors")
    assert ie_parameter_otype("pixelspectralqe") == ("pixel", "pixelspectralqe")
    assert ie_parameter_otype("pdspectralqe") == ("pixel", "pdspectralqe")
    assert ie_parameter_otype("pixelqe") == ("pixel", "pixelqe")
    assert ie_parameter_otype("spectralsr") == ("pixel", "spectralsr")
    assert ie_parameter_otype("pdspectralsr") == ("pixel", "pdspectralsr")
    assert ie_parameter_otype("pixelspectralsr") == ("pixel", "pixelspectralsr")
    assert ie_parameter_otype("sr") == ("pixel", "sr")
    assert ie_parameter_otype("dynamic range") == ("sensor", "dynamicrange")
    assert ie_parameter_otype("shotnoiseflag") == ("sensor", "shotnoiseflag")
    assert ie_parameter_otype("shot noise flag") == ("sensor", "shotnoiseflag")
    assert ie_parameter_otype("blacklevel") == ("sensor", "blacklevel")
    assert ie_parameter_otype("black level") == ("sensor", "blacklevel")
    assert ie_parameter_otype("zerolevel") == ("sensor", "zerolevel")
    assert ie_parameter_otype("zero level") == ("sensor", "zerolevel")
    assert ie_parameter_otype("bits") == ("sensor", "bits")
    assert ie_parameter_otype("voltage") == ("sensor", "voltage")
    assert ie_parameter_otype("scene_name") == ("sensor", "scene_name")
    assert ie_parameter_otype("scenename") == ("sensor", "scenename")
    assert ie_parameter_otype("scene name") == ("sensor", "scenename")
    assert ie_parameter_otype("metadata scene name") == ("sensor", "metadatascenename")
    assert ie_parameter_otype("metadatascenename") == ("sensor", "metadatascenename")
    assert ie_parameter_otype("lens") == ("sensor", "lens")
    assert ie_parameter_otype("metadata lens") == ("sensor", "metadatalens")
    assert ie_parameter_otype("metadata lensname") == ("sensor", "metadatalensname")
    assert ie_parameter_otype("metadataopticsname") == ("sensor", "metadataopticsname")
    assert ie_parameter_otype("metadata optics name") == ("sensor", "metadataopticsname")
    assert ie_parameter_otype("metadatasensorname") == ("sensor", "metadatasensorname")
    assert ie_parameter_otype("metadata sensor name") == ("sensor", "metadatasensorname")
    assert ie_parameter_otype("metadatacrop") == ("sensor", "metadatacrop")
    assert ie_parameter_otype("metadata crop") == ("sensor", "metadatacrop")
    assert ie_parameter_otype("ml") == ("sensor", "ml")
    assert ie_parameter_otype("mlens") == ("sensor", "mlens")
    assert ie_parameter_otype("ulens") == ("sensor", "ulens")
    assert ie_parameter_otype("microlens offset") == ("sensor", "microlensoffset")
    assert ie_parameter_otype("mloffset") == ("sensor", "mloffset")
    assert ie_parameter_otype("microlens offset microns") == ("sensor", "microlensoffsetmicrons")
    assert ie_parameter_otype("vignettingflag") == ("sensor", "vignettingflag")
    assert ie_parameter_otype("vignetting flag") == ("sensor", "vignettingflag")
    assert ie_parameter_otype("pixelvignetting") == ("sensor", "pixelvignetting")
    assert ie_parameter_otype("pixel vignetting") == ("sensor", "pixelvignetting")
    assert ie_parameter_otype("sensorvignetting") == ("sensor", "sensorvignetting")
    assert ie_parameter_otype("sensor vignetting") == ("sensor", "vignetting")
    assert ie_parameter_otype("bare etendue") == ("sensor", "bareetendue")
    assert ie_parameter_otype("sensorbareetendue") == ("sensor", "sensorbareetendue")
    assert ie_parameter_otype("sensor bare etendue") == ("sensor", "bareetendue")
    assert ie_parameter_otype("nomicrolensetendue") == ("sensor", "nomicrolensetendue")
    assert ie_parameter_otype("no microlens etendue") == ("sensor", "nomicrolensetendue")
    assert ie_parameter_otype("vignettingname") == ("sensor", "vignettingname")
    assert ie_parameter_otype("vignetting name") == ("sensor", "vignettingname")
    assert ie_parameter_otype("color") == ("sensor", "color")
    assert ie_parameter_otype("digitalvalue") == ("sensor", "digitalvalue")
    assert ie_parameter_otype("digital value") == ("sensor", "digitalvalue")
    assert ie_parameter_otype("digitalvalues") == ("sensor", "digitalvalues")
    assert ie_parameter_otype("digital values") == ("sensor", "digitalvalues")
    assert ie_parameter_otype("electron") == ("sensor", "electron")
    assert ie_parameter_otype("electrons per area") == ("sensor", "electronsperarea")
    assert ie_parameter_otype("filternamescellarray") == ("sensor", "filternamescellarray")
    assert ie_parameter_otype("filter names cell array") == ("sensor", "filternamescellarray")
    assert ie_parameter_otype("filtercolornamescellarray") == ("sensor", "filtercolornamescellarray")
    assert ie_parameter_otype("filter color names cell array") == ("sensor", "filtercolornamescellarray")
    assert ie_parameter_otype("filternamescell") == ("sensor", "filternamescell")
    assert ie_parameter_otype("filter names cell") == ("sensor", "filternamescell")
    assert ie_parameter_otype("lut") == ("sensor", "lut")
    assert ie_parameter_otype("quantizationlut") == ("sensor", "quantizationlut")
    assert ie_parameter_otype("quantization lut") == ("sensor", "quantizationlut")
    assert ie_parameter_otype("qmethod") == ("sensor", "qmethod")
    assert ie_parameter_otype("qMethod") == ("sensor", "qmethod")
    assert ie_parameter_otype("quantizationstructure") == ("sensor", "quantizationstructure")
    assert ie_parameter_otype("quantization structure") == ("sensor", "quantizationstructure")
    assert ie_parameter_otype("cfapattern") == ("sensor", "cfapattern")
    assert ie_parameter_otype("cfaname") == ("sensor", "cfaname")
    assert ie_parameter_otype("unitblockconfig") == ("sensor", "unitblockconfig")
    assert ie_parameter_otype("sensorspectrum") == ("sensor", "sensorspectrum")
    assert ie_parameter_otype("wavelengthresolution") == ("sensor", "wavelengthresolution")
    assert ie_parameter_otype("binwidth") == ("sensor", "binwidth")
    assert ie_parameter_otype("numberofwavelengthsamples") == ("sensor", "numberofwavelengthsamples")
    assert ie_parameter_otype("dvorvolts") == ("sensor", "dvorvolts")
    assert ie_parameter_otype("dv or volts") == ("sensor", "dvorvolts")
    assert ie_parameter_otype("digitalorvolts") == ("sensor", "digitalorvolts")
    assert ie_parameter_otype("digital or volts") == ("sensor", "digitalorvolts")
    assert ie_parameter_otype("voltimages") == ("sensor", "voltimages")
    assert ie_parameter_otype("volt images") == ("sensor", "voltimages")
    assert ie_parameter_otype("fill factor") == ("pixel", "fillfactor")
    assert ie_parameter_otype("conversion gain") == ("pixel", "conversiongain")
    assert ie_parameter_otype("conversiongainvpelectron") == ("pixel", "conversiongainvpelectron")
    assert ie_parameter_otype("conversion gain v per electron") == ("pixel", "conversiongainvperelectron")
    assert ie_parameter_otype("vswing") == ("pixel", "vswing")
    assert ie_parameter_otype("well capacity") == ("pixel", "wellcapacity")
    assert ie_parameter_otype("volts per electron") == ("pixel", "voltsperelectron")
    assert ie_parameter_otype("saturation voltage") == ("pixel", "saturationvoltage")
    assert ie_parameter_otype("max voltage") == ("pixel", "maxvoltage")
    assert ie_parameter_otype("dark current density") == ("pixel", "darkcurrentdensity")
    assert ie_parameter_otype("dark current per pixel") == ("pixel", "darkcurrentperpixel")
    assert ie_parameter_otype("darkvolt") == ("pixel", "darkvolt")
    assert ie_parameter_otype("darkvolts") == ("pixel", "darkvolts")
    assert ie_parameter_otype("dark voltage per pixel") == ("pixel", "darkvoltageperpixel")
    assert ie_parameter_otype("volts per second") == ("pixel", "voltspersecond")
    assert ie_parameter_otype("read noise") == ("pixel", "readnoise")
    assert ie_parameter_otype("read noise volts") == ("pixel", "readnoisevolts")
    assert ie_parameter_otype("read standard deviation volts") == ("pixel", "readstandarddeviationvolts")
    assert ie_parameter_otype("read standard deviation electrons") == ("pixel", "readstandarddeviationelectrons")
    assert ie_parameter_otype("read noise std volts") == ("pixel", "readnoisestdvolts")
    assert ie_parameter_otype("read noise millivolts") == ("pixel", "readnoisemillivolts")
    assert ie_parameter_otype("width gap") == ("pixel", "widthgap")
    assert ie_parameter_otype("width between pixels") == ("pixel", "widthbetweenpixels")
    assert ie_parameter_otype("height between pixels") == ("pixel", "heightbetweenpixels")
    assert ie_parameter_otype("pixel width meters") == ("pixel", "widthmeters")
    assert ie_parameter_otype("pixel height meters") == ("pixel", "heightmeters")
    assert ie_parameter_otype("pd width") == ("pixel", "pdwidth")
    assert ie_parameter_otype("pd dimension") == ("pixel", "pddimension")
    assert ie_parameter_otype("layer thicknesses") == ("pixel", "layerthicknesses")
    assert ie_parameter_otype("refractive index") == ("pixel", "refractiveindex")
    assert ie_parameter_otype("refractive indices") == ("pixel", "refractiveindices")
    assert ie_parameter_otype("n") == ("pixel", "n")
    assert ie_parameter_otype("stack height") == ("pixel", "stackheight")
    assert ie_parameter_otype("pixel depth meters") == ("pixel", "depthmeters")
    assert ie_parameter_otype("pd xpos") == ("pixel", "pdxpos")
    assert ie_parameter_otype("photodetector x position") == ("pixel", "photodetectorxposition")
    assert ie_parameter_otype("pd position") == ("pixel", "pdposition")
    assert ie_parameter_otype("quantum efficiency") == ("pixel", "quantumefficiency")
    assert ie_parameter_otype("pixel quantum efficiency") == ("pixel", "quantumefficiency")
    assert ie_parameter_otype("photodetector quantum efficiency") == ("pixel", "photodetectorquantumefficiency")
    assert ie_parameter_otype("photodetector spectral quantum efficiency") == ("pixel", "photodetectorspectralquantumefficiency")
    assert ie_parameter_otype("diffusion MTF") == ("sensor", "diffusionmtf")
    assert ie_parameter_otype("ag") == ("sensor", "ag")
    assert ie_parameter_otype("ao") == ("sensor", "ao")
    assert ie_parameter_otype("human cone densities") == ("sensor", "humanconedensities")
    assert ie_parameter_otype("human cone seed") == ("sensor", "humanconeseed")
    assert ie_parameter_otype("mcccornerpoints") == ("sensor", "mcccornerpoints")
    assert ie_parameter_otype("mcc corner points") == ("sensor", "mcccornerpoints")
    assert ie_parameter_otype("mccrecthandles") == ("sensor", "mccrecthandles")
    assert ie_parameter_otype("mcc rect handles") == ("sensor", "mccrecthandles")
    assert ie_parameter_otype("consistency") == ("sensor", "consistency")
    assert ie_parameter_otype("sensor consistency") == ("sensor", "consistency")
    assert ie_parameter_otype("sensor compute") == ("sensor", "compute")
    assert ie_parameter_otype("sensor compute method") == ("sensor", "computemethod")
    assert ie_parameter_otype("integration time") == ("sensor", "integrationtime")
    assert ie_parameter_otype("exptimes") == ("sensor", "exptimes")
    assert ie_parameter_otype("unique exptimes") == ("sensor", "uniqueexptimes")
    assert ie_parameter_otype("central exposure") == ("sensor", "centralexposure")
    assert ie_parameter_otype("centralexposure") == ("sensor", "centralexposure")
    assert ie_parameter_otype("exposuremethod") == ("sensor", "exposuremethod")
    assert ie_parameter_otype("exposure method") == ("sensor", "exposuremethod")
    assert ie_parameter_otype("nexposures") == ("sensor", "nexposures")
    assert ie_parameter_otype("n exposures") == ("sensor", "nexposures")
    assert ie_parameter_otype("exposureplane") == ("sensor", "exposureplane")
    assert ie_parameter_otype("exposure plane") == ("sensor", "exposureplane")
    assert ie_parameter_otype("correlateddoublesampling") == ("sensor", "correlateddoublesampling")
    assert ie_parameter_otype("correlated double sampling") == ("sensor", "correlateddoublesampling")
    assert ie_parameter_otype("autoexp") == ("sensor", "autoexp")
    assert ie_parameter_otype("autoexposure") == ("sensor", "autoexposure")
    assert ie_parameter_otype("auto exposure") == ("sensor", "autoexposure")
    assert ie_parameter_otype("automaticexposure") == ("sensor", "automaticexposure")
    assert ie_parameter_otype("automatic exposure") == ("sensor", "automaticexposure")
    assert ie_parameter_otype("pixelsamples") == ("sensor", "pixelsamples")
    assert ie_parameter_otype("pixel samples") == ("sensor", "pixelsamples")
    assert ie_parameter_otype("npixelsamplesforcomputing") == ("sensor", "npixelsamplesforcomputing")
    assert ie_parameter_otype("n pixel samples for computing") == ("sensor", "npixelsamplesforcomputing")
    assert ie_parameter_otype("spatialsamplesperpixel") == ("sensor", "spatialsamplesperpixel")
    assert ie_parameter_otype("spatial samples per pixel") == ("sensor", "spatialsamplesperpixel")
    assert ie_parameter_otype("reusenoise") == ("sensor", "reusenoise")
    assert ie_parameter_otype("noiseseed") == ("sensor", "noiseseed")
    assert ie_parameter_otype("responsetype") == ("sensor", "responsetype")
    assert ie_parameter_otype("response type") == ("sensor", "responsetype")
    assert ie_parameter_otype("eye movement") == ("sensor", "eyemovement")
    assert ie_parameter_otype("eyemovement") == ("sensor", "eyemovement")
    assert ie_parameter_otype("movementpositions") == ("sensor", "movementpositions")
    assert ie_parameter_otype("movement positions") == ("sensor", "movementpositions")
    assert ie_parameter_otype("sensorpositions") == ("sensor", "sensorpositions")
    assert ie_parameter_otype("sensor positions") == ("sensor", "positions")
    assert ie_parameter_otype("sensorpositionsx") == ("sensor", "sensorpositionsx")
    assert ie_parameter_otype("sensor positions x") == ("sensor", "positionsx")
    assert ie_parameter_otype("sensorpositionsy") == ("sensor", "sensorpositionsy")
    assert ie_parameter_otype("sensor positions y") == ("sensor", "positionsy")
    assert ie_parameter_otype("framesperposition") == ("sensor", "framesperposition")
    assert ie_parameter_otype("frames per position") == ("sensor", "framesperposition")
    assert ie_parameter_otype("exposuretimesperposition") == ("sensor", "exposuretimesperposition")
    assert ie_parameter_otype("exposure times per position") == ("sensor", "exposuretimesperposition")
    assert ie_parameter_otype("etimeperpos") == ("sensor", "etimeperpos")
    assert ie_parameter_otype("etime per pos") == ("sensor", "etimeperpos")
    assert ie_parameter_otype("human") == ("sensor", "human")
    assert ie_parameter_otype("cone type") == ("sensor", "conetype")
    assert ie_parameter_otype("humanconetype") == ("sensor", "humanconetype")
    assert ie_parameter_otype("human cone type") == ("sensor", "humanconetype")
    assert ie_parameter_otype("densities") == ("sensor", "densities")
    assert ie_parameter_otype("humanconedensities") == ("sensor", "humanconedensities")
    assert ie_parameter_otype("cone xy") == ("sensor", "conexy")
    assert ie_parameter_otype("cone locs") == ("sensor", "conelocs")
    assert ie_parameter_otype("xy") == ("sensor", "xy")
    assert ie_parameter_otype("humanconelocs") == ("sensor", "humanconelocs")
    assert ie_parameter_otype("human cone locs") == ("sensor", "humanconelocs")
    assert ie_parameter_otype("rseed") == ("sensor", "rseed")
    assert ie_parameter_otype("human rseed") == ("sensor", "humanrseed")
    assert ie_parameter_otype("humanrseed") == ("sensor", "humanrseed")
    assert ie_parameter_otype("humanconeseed") == ("sensor", "humanconeseed")
    assert ie_parameter_otype("chart parameters") == ("sensor", "chartparameters")
    assert ie_parameter_otype("chartparameters") == ("sensor", "chartparameters")
    assert ie_parameter_otype("corner points") == ("sensor", "cornerpoints")
    assert ie_parameter_otype("cornerpoints") == ("sensor", "cornerpoints")
    assert ie_parameter_otype("chart corner points") == ("sensor", "chartcornerpoints")
    assert ie_parameter_otype("chartcornerpoints") == ("sensor", "chartcornerpoints")
    assert ie_parameter_otype("chart corners") == ("sensor", "chartcorners")
    assert ie_parameter_otype("chartcorners") == ("sensor", "chartcorners")
    assert ie_parameter_otype("chart rects") == ("sensor", "chartrects")
    assert ie_parameter_otype("chartrects") == ("sensor", "chartrects")
    assert ie_parameter_otype("chart rectangles") == ("sensor", "chartrectangles")
    assert ie_parameter_otype("chartrectangles") == ("sensor", "chartrectangles")
    assert ie_parameter_otype("current rect") == ("sensor", "currentrect")
    assert ie_parameter_otype("currentrect") == ("sensor", "currentrect")
    assert ie_parameter_otype("chart current rect") == ("sensor", "chartcurrentrect")
    assert ie_parameter_otype("chartcurrentrect") == ("sensor", "chartcurrentrect")
    assert ie_parameter_otype("mccrecthandles") == ("sensor", "mccrecthandles")
    assert ie_parameter_otype("scene name") == ("sensor", "scenename")
    assert ie_parameter_otype("metadata scene name") == ("sensor", "metadatascenename")
    assert ie_parameter_otype("metadatalensname") == ("sensor", "metadatalensname")
    assert ie_parameter_otype("metadata lens name") == ("sensor", "metadatalensname")
    assert ie_parameter_otype("metadatalens") == ("sensor", "metadatalens")
    assert ie_parameter_otype("metadata lens") == ("sensor", "metadatalens")
    assert ie_parameter_otype("metadata optics name") == ("sensor", "metadataopticsname")
    assert ie_parameter_otype("metadata sensor name") == ("sensor", "metadatasensorname")
    assert ie_parameter_otype("metadata crop") == ("sensor", "metadatacrop")
    assert ie_parameter_otype("fnumber") == ("optics", "fnumber")
    assert ie_parameter_otype("asset light") == ("asset", "assetlight")
    assert ieParameterOtype("ip display") == ("ip", "display")


def test_ie_parameter_otype_returns_empty_type_for_ambiguous_or_unknown_params() -> None:
    assert ie_parameter_otype("size") == ("", "size")
    assert ie_parameter_otype("mystery parameter") == ("", "mysteryparameter")
