#!/usr/bin/env python3
"""Quasi-static TG/FD terminal diagnostic for the open-source split-PD deck.

This is not a true time-domain pinned-photodiode transfer simulation.  It adds a
real DEVSIM floating-diffusion terminal on the 2D mesh, scales the configured
transfer-gate barrier feature, and measures terminal current deltas under the
same imported FDTD generation map.  The output is useful for detecting whether
TG/FD parameters are electrically wired into the solver instead of being only
metadata.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import subprocess
import sys
from copy import deepcopy
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent


@dataclass(frozen=True)
class TGFDConfig:
    generation_map_npz: Path
    measured_profile: Path
    output_dir: Path
    cases: tuple[str, ...] = ("center", "edge20x")
    wavelength_nm: float = 550.0
    tg_barrier_scales: tuple[float, ...] = (1.0, 0.5, 0.1, 0.0)
    width_um: float = 1.4
    depth_um: float = 3.0
    split_gap_um: float = 0.04
    mesh_um: float = 0.10
    fine_mesh_um: float = 0.025
    reverse_bias_v: float = -1.0
    floating_diffusion_bias_v: float = 0.0
    force: bool = False


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def parse_csv(text: str) -> tuple[str, ...]:
    return tuple(part.strip() for part in text.split(",") if part.strip())


def parse_float_csv(text: str) -> tuple[float, ...]:
    return tuple(float(part.strip()) for part in text.split(",") if part.strip())


def safe_scale(scale: float) -> str:
    return f"{scale:.3f}".replace(".", "p").replace("-", "m")


def run_command(command: list[str], log_path: Path) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log:
        log.write(" ".join(command) + "\n\n")
        result = subprocess.run(
            command,
            cwd=ROOT,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
    if result.returncode != 0:
        tail = "\n".join(log_path.read_text(encoding="utf-8", errors="replace").splitlines()[-60:])
        raise RuntimeError(f"command failed; see {log_path}\n{tail}")


def build_fd_mesh(config: TGFDConfig) -> Path:
    mesh_dir = config.output_dir / "gmsh_fd_contact_mesh"
    mesh_path = mesh_dir / "split_pixel_2d.msh"
    if mesh_path.exists() and not config.force:
        return mesh_path
    command = [
        sys.executable,
        str(ROOT / "tcad_gmsh_pixel_mesh.py"),
        "--dimension",
        "2",
        "--measured-profile",
        str(config.measured_profile),
        "--width-um",
        f"{config.width_um:g}",
        "--depth-um",
        f"{config.depth_um:g}",
        "--split-gap-um",
        f"{config.split_gap_um:g}",
        "--mesh-um",
        f"{config.mesh_um:g}",
        "--fine-mesh-um",
        f"{config.fine_mesh_um:g}",
        "--include-fd-contact",
        "--output-dir",
        str(mesh_dir),
    ]
    run_command(command, mesh_dir / "mesh.log")
    return mesh_path


def scaled_profile(config: TGFDConfig, scale: float) -> Path:
    source = read_json(config.measured_profile)
    profile = deepcopy(source)
    applied = []
    for feature in profile.get("electrical_features", []):
        if str(feature.get("role", "")).lower() != "transfer_gate_barrier":
            continue
        for key in ("acceptor_cm3", "donor_cm3"):
            if key in feature:
                feature[key] = float(feature[key]) * scale
        feature["tg_barrier_scale_applied"] = scale
        applied.append(feature.get("name", "transfer_gate_barrier"))
    profile.setdefault("notes", []).append(
        f"Generated by devsim_tg_fd_transfer_sweep_2d.py with transfer_gate_barrier scale={scale:g}."
    )
    profile["tg_fd_diagnostic"] = {
        "source_profile": str(config.measured_profile),
        "transfer_gate_barrier_scale": scale,
        "scaled_features": applied,
    }
    path = config.output_dir / "profiles" / f"profile_tg_scale_{safe_scale(scale)}.json"
    write_json(path, profile)
    return path


def run_case(config: TGFDConfig, mesh_path: Path, profile_path: Path, case: str, scale: float) -> dict[str, Any]:
    run_dir = config.output_dir / "runs" / f"{case}_tg_scale_{safe_scale(scale)}"
    summary_path = run_dir / "summary.json"
    if not summary_path.exists() or config.force:
        command = [
            sys.executable,
            str(ROOT / "devsim_split_pd_2d.py"),
            "--mesh-source",
            "gmsh",
            "--gmsh-mesh",
            str(mesh_path),
            "--width-um",
            f"{config.width_um:g}",
            "--depth-um",
            f"{config.depth_um:g}",
            "--split-gap-um",
            f"{config.split_gap_um:g}",
            "--generation-map-npz",
            str(config.generation_map_npz),
            "--generation-profile-case",
            case,
            "--generation-profile-wavelength-nm",
            f"{config.wavelength_nm:g}",
            "--electrical-model",
            "profile-ppd",
            "--measured-profile",
            str(profile_path),
            "--reverse-bias-v",
            f"{config.reverse_bias_v:g}",
            "--floating-diffusion-bias-v",
            f"{config.floating_diffusion_bias_v:g}",
            "--output-dir",
            str(run_dir),
        ]
        run_command(command, run_dir / "run.log")
    summary = read_json(summary_path)
    deltas = summary.get("contact_photo_deltas", {})
    fd = deltas.get("floating_diffusion", {})
    left = deltas.get("cathode_left", {})
    right = deltas.get("cathode_right", {})
    fd_e = float(fd.get("electron_delta_a_per_cm", math.nan))
    left_e = float(left.get("electron_delta_a_per_cm", math.nan))
    right_e = float(right.get("electron_delta_a_per_cm", math.nan))
    denom = sum(abs(value) for value in (fd_e, left_e, right_e) if math.isfinite(value))
    return {
        "case": case,
        "wavelength_nm": config.wavelength_nm,
        "tg_barrier_scale": scale,
        "floating_diffusion_electron_delta_a_per_cm": fd_e,
        "cathode_left_electron_delta_a_per_cm": left_e,
        "cathode_right_electron_delta_a_per_cm": right_e,
        "fd_abs_fraction_of_fd_plus_cathodes": abs(fd_e) / denom if denom else math.nan,
        "split_phase_x": summary.get("photo_split_phase_x_proxy", math.nan),
        "terminal_balance_illuminated_a_per_cm": summary.get(
            "terminal_current_balance_illuminated_a_per_cm", math.nan
        ),
        "generation_integral_rel_error": summary.get("generation_integral_summary", {}).get(
            "mesh_to_target_rel_error", math.nan
        ),
        "summary_json": str(summary_path),
    }


def run(config: TGFDConfig) -> dict[str, Any]:
    config.output_dir.mkdir(parents=True, exist_ok=True)
    mesh_path = build_fd_mesh(config)
    rows: list[dict[str, Any]] = []
    for scale in config.tg_barrier_scales:
        profile_path = scaled_profile(config, scale)
        for case in config.cases:
            rows.append(run_case(config, mesh_path, profile_path, case, scale))
    summary_csv = config.output_dir / "tg_fd_transfer_sweep_summary.csv"
    report_json = config.output_dir / "tg_fd_transfer_sweep_report.json"
    write_csv(summary_csv, rows)
    fd_fractions = [
        float(row["fd_abs_fraction_of_fd_plus_cathodes"])
        for row in rows
        if math.isfinite(float(row["fd_abs_fraction_of_fd_plus_cathodes"]))
    ]
    balances = [
        abs(float(row["terminal_balance_illuminated_a_per_cm"]))
        for row in rows
        if math.isfinite(float(row["terminal_balance_illuminated_a_per_cm"]))
    ]
    report = {
        "schema": "devsim_tg_fd_transfer_sweep_2d_v1",
        "method": "quasi_static_transfer_gate_barrier_sweep_with_fd_terminal",
        "product_accuracy_ready": False,
        "config": {
            **asdict(config),
            "generation_map_npz": str(config.generation_map_npz),
            "measured_profile": str(config.measured_profile),
            "output_dir": str(config.output_dir),
        },
        "mesh": str(mesh_path),
        "row_count": len(rows),
        "max_fd_abs_fraction": max(fd_fractions) if fd_fractions else math.nan,
        "min_fd_abs_fraction": min(fd_fractions) if fd_fractions else math.nan,
        "terminal_balance_max_abs_a_per_cm": max(balances) if balances else math.nan,
        "outputs": {
            "summary_csv": str(summary_csv),
            "report_json": str(report_json),
        },
        "rows": rows,
        "limitations": [
            "This is a quasi-static terminal diagnostic, not a time-domain pinned-photodiode transfer simulation.",
            "TG is represented by scaling the configured transfer_gate_barrier doping feature.",
            "FD is a real DEVSIM semiconductor terminal on the 2D top boundary, but oxide/gate electrostatics and transient charge packets are not yet modeled.",
        ],
    }
    write_json(report_json, report)
    print(json.dumps(report, indent=2))
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--generation-map-npz",
        type=Path,
        default=ROOT / "runs/fdtd_to_tcad_generation_2d_cra_smoke/tcad_generation_map_2d.npz",
    )
    parser.add_argument(
        "--measured-profile",
        type=Path,
        default=ROOT / "measured_profiles/reference_cmos_ppd_1p4um/profile.json",
    )
    parser.add_argument("--output-dir", type=Path, default=ROOT / "runs/devsim_tg_fd_transfer_sweep_2d_reference")
    parser.add_argument("--cases", default="center,edge20x")
    parser.add_argument("--wavelength-nm", type=float, default=550.0)
    parser.add_argument("--tg-barrier-scales", default="1.0,0.5,0.1,0.0")
    parser.add_argument("--width-um", type=float, default=1.4)
    parser.add_argument("--depth-um", type=float, default=3.0)
    parser.add_argument("--split-gap-um", type=float, default=0.04)
    parser.add_argument("--mesh-um", type=float, default=0.10)
    parser.add_argument("--fine-mesh-um", type=float, default=0.025)
    parser.add_argument("--reverse-bias-v", type=float, default=-1.0)
    parser.add_argument("--floating-diffusion-bias-v", type=float, default=0.0)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    run(
        TGFDConfig(
            generation_map_npz=args.generation_map_npz,
            measured_profile=args.measured_profile,
            output_dir=args.output_dir,
            cases=parse_csv(args.cases),
            wavelength_nm=args.wavelength_nm,
            tg_barrier_scales=parse_float_csv(args.tg_barrier_scales),
            width_um=args.width_um,
            depth_um=args.depth_um,
            split_gap_um=args.split_gap_um,
            mesh_um=args.mesh_um,
            fine_mesh_um=args.fine_mesh_um,
            reverse_bias_v=args.reverse_bias_v,
            floating_diffusion_bias_v=args.floating_diffusion_bias_v,
            force=args.force,
        )
    )


if __name__ == "__main__":
    main()
